[package]
name = "match"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet-0.33.0" }
DeepBook = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "devnet-0.33.0" }

[addresses]
match =  "0x0"
sui =  "0000000000000000000000000000000000000000000000000000000000000002"
deepbook = "0xdee9"
